version: 2

updates:

  # Update npm packages
  - package-ecosystem: npm
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      interval: daily
    versioning-strategy: increase

    allow:
      - dependency-type: direct

    ignore:
      # Ignore major updates (@axe-core/puppeteer peer puppeteer <= 18)
      - dependency-name: puppeteer
        update-types: ['version-update:semver-major']

      # Ignore major/minor updates (Marked parser changes output)
      - dependency-name: jstransformer-marked
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      
      # Always ignore legacy packages (Maintain rollup's IE8 compatibility)
      - dependency-name: rollup

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - alphagov/design-system-developers
    schedule:
      interval: daily
