# Override default `deploy/public` build directory used by legacy branches
# https://app.netlify.com/sites/govuk-design-system-preview/configuration/deploys

[build]
  publish = "build"

# A number of the examples in the Design System include <form> elements so that
# users copying the examples have something that requires relatively little
# tweaking to work out the box (in particular Prototype Kit users, for example)
#
# We have some JavaScript to prevent those forms actually being submitted but
# for users who don’t have JavaScript enabled (or who manage to interact with
# the form before the JS has run) it’s still possible to submit the form.
#
# Handle that gracefully by redirecting to a page that explains what has
# happened and what the user needs to do next.
#
# POST requests work just fine. Requires examples to be set up with an action of
# `/form-handler`.

[[redirects]]
  from = "/form-handler"
  to = "/form-success"
  status = 301

# Proxy requests for security.txt to the centralised Cabinet Office
# vulnerability disclosure policy (VDP)
#
# https://github.com/alphagov/security.txt

[[redirects]]
  from = "/.well-known/security.txt"
  to = "https://vdp.cabinetoffice.gov.uk/.well-known/security.txt"
  status = 200 # Proxy rather than redirect

[[redirects]]
  from = "/security.txt"
  to = "https://vdp.cabinetoffice.gov.uk/.well-known/security.txt"
  status = 200 # Proxy rather than redirect

[[redirects]]
  from = "/community/backlog/"
  to = "/community/upcoming-components-patterns/"
  status = 301

[[redirects]]
  from = "/community/how-you-can-contribute/"
  to = "/community/"
  status = 301

[[redirects]]
  from = "/community/call-for-speakers-2023/"
  to = "/community/design-system-day/"
  status = 301

[[redirects]]
  from = "/community/design-system-day/session-information/"
  to = "/community/design-system-day/"
  status = 302 # We will bring this page back in future so it is not a permanent redirect

[[redirects]]
  from = "/patterns/ethnic-group/"
  to = "/patterns/equality-information/"
  status = 301

[[redirects]]
  from = "/patterns/start-pages/"
  to = "/patterns/start-using-a-service/"
  status = 301

[[redirects]]
  from = "/patterns/task-list-pages/"
  to = "/patterns/complete-multiple-tasks/"
  status = 301

[[redirects]]
  from = "/patterns/understand-the-impact-of-an-emergency/"
  to = "/components/notification-banner/"
  status = 301